[package]
name = "easy-pinyin"
version = "0.2.0"
entrypoint = "lib.typ"
authors = ["7sDream <@7sDream>", "Other open-source contributors"]
license = "MIT"
description = "Convert Chinese characters to pinyin with ruby annotations."
repository = "https://github.com/7sDream/typst-easy-pinyin"
keywords = ["pinyin", "chinese", "ruby", "annotation", "linguistics"]
categories = ["text", "utility"]
compiler = "0.14.0"
exclude = [
    "tests/",
    "wasm/",
    "rust-pinyin/",
    "Justfile",
    ".gitignore",
    ".gitmodules",
]
